"""добавили секретный код

Revision ID: 0c7b57f5d362
Revises: fc225efbd8b6
Create Date: 2022-04-24 20:19:35.659231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7b57f5d362'
down_revision = 'fc225efbd8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_code', sa.String(), nullable=True))
    op.drop_column('users', 'shopping_cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shopping_cart', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'security_code')
    # ### end Alembic commands ###
