"""Добавление колонки штрих-кода

Revision ID: 10e33cda1449
Revises: de8a315e6b57
Create Date: 2022-07-27 15:54:56.311109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e33cda1449'
down_revision = 'de8a315e6b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('barcode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'barcode')
    # ### end Alembic commands ###
