"""добавлен статус досутпа и изменено стандартное значение рейтинга

Revision ID: 34d252b1264d
Revises: 
Create Date: 2022-03-31 16:43:31.368577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d252b1264d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rights', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rights')
    # ### end Alembic commands ###
