"""изменение отображения даты user

Revision ID: 4bbe41ad6f97
Revises: 9da873b66b29
Create Date: 2022-03-31 19:23:22.695430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbe41ad6f97'
down_revision = '9da873b66b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
