"""добавил стандартное значение в столбце avatar

Revision ID: 5beba143c6ad
Revises: 5fe19fb5a25a
Create Date: 2022-04-27 21:23:29.884503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5beba143c6ad'
down_revision = '5fe19fb5a25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
