"""добавление стандартного значения в столбце avatar

Revision ID: 5fe19fb5a25a
Revises: 4947a4a0a1b0
Create Date: 2022-04-27 21:14:41.100305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe19fb5a25a'
down_revision = '4947a4a0a1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
