"""добавление классов

Revision ID: 6c7b727332aa
Revises: 4bbe41ad6f97
Create Date: 2022-03-31 20:59:20.615036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7b727332aa'
down_revision = '4bbe41ad6f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('limitation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('parallel_number_student', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('letter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'letter')
    op.drop_column('users', 'parallel_number_student')
    op.drop_column('books', 'limitation')
    # ### end Alembic commands ###
