"""добавление колонки штрих-кода

Revision ID: 6f2d19857404
Revises: 2ef03d5aea93
Create Date: 2022-07-05 12:53:29.707518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2d19857404'
down_revision = '2ef03d5aea93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('barcode', sa.String(), nullable=True))
    op.alter_column('books', 'year_publishing',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'year_publishing',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('books', 'barcode')
    # ### end Alembic commands ###
