"""Добавление колонки для ссылки в электронной версии

Revision ID: 7901dff01bc6
Revises: ca6699205f78
Create Date: 2022-07-28 14:15:37.723633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7901dff01bc6'
down_revision = 'ca6699205f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('electronic version', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('electronic version', 'link')
    # ### end Alembic commands ###
