"""добавление хеширования пароля

Revision ID: 9da873b66b29
Revises: f7d7f075985a
Create Date: 2022-03-31 19:16:10.735183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da873b66b29'
down_revision = 'f7d7f075985a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
