"""Добавление колонки электронной версии

Revision ID: ca6699205f78
Revises: 10e33cda1449
Create Date: 2022-07-27 16:06:57.744492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6699205f78'
down_revision = '10e33cda1449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('electronic_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'electronic_version')
    # ### end Alembic commands ###
