"""Добавление колонок: издательство, год издания, количество страниц

Revision ID: de8a315e6b57
Revises: 5beba143c6ad
Create Date: 2022-07-27 15:38:50.990163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8a315e6b57'
down_revision = '5beba143c6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publishing_house', sa.String(), nullable=True))
    op.add_column('books', sa.Column('year_publishing', sa.String(), nullable=True))
    op.add_column('books', sa.Column('number_of_pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'number_of_pages')
    op.drop_column('books', 'year_publishing')
    op.drop_column('books', 'publishing_house')
    # ### end Alembic commands ###
