"""изменение отображения даты

Revision ID: f7d7f075985a
Revises: 34d252b1264d
Create Date: 2022-03-31 19:11:05.201977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d7f075985a'
down_revision = '34d252b1264d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
