"""столбец корзины

Revision ID: fc225efbd8b6
Revises: 55d340c4cce8
Create Date: 2022-04-22 18:13:53.139412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc225efbd8b6'
down_revision = '55d340c4cce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shopping_cart', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shopping_cart')
    # ### end Alembic commands ###
